name: AntiCombatLog
version: ${project.version}
main: net.badbird5907.anticombatlog.AntiCombatLog
api-version: 1.13
softdepend:
  - floodgate
  - AdvancedEnchantments
  - ExcellentEnchants
  - Duels
  - Citizens
commands:
  anticombatlog:
    description: main command
    aliases: [anticombatlog]
  resettag:
    description: reset combat tag
    aliases: [resetcombattag]
    permission: anticombatlog.command.resettag
permissions:
  anticombatlog.admin:
    description: nags about updates
    default: op
  anticombatlog.reload:
    description: reloads the config
    default: op
