name: BankSys
depend: [WorldEdit, Citizens, eco]
version: '${project.version}'
main: com.stardust.banksys.BankSys
api-version: '1.20'
authors: [ travis, ahmed ]
commands:
  bank:
    description: "BankSys commands"
    usage: /bank [command]

